### ISSUE TITLE
ignore_flag is not working

### ISSUE THREAD

**Issue by jklare** [sensu-plugins/sensu-plugins-ceph#6]
Hi,

i already commented on the patch that broke functionality for the ignore_flag. I can push up a fix for this, but am not sure if this repo is still maintained or active. Please let me know if i should push a patch.

Cheers,
Jan

**Comment by majormoses** [comment]
It is certainly still maintained and I welcome a PR.

**Comment by majormoses** [comment]
Thanks for the contribution!

**Comment by majormoses** [comment]
closed via #7

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-ceph/versions/1.0.1
